[tool.ruff]
line-length = 120
lint.ignore = ["E501"]
exclude=["docs"]
[tool.black]
line-length = 120
[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [ "tests", "src" ]
norecursedirs = [".env", "data", "maps", ".github", ".vscode"]
console_output_style = "count"
addopts = "--cov-branch --cov=dabs-skid --cov-report term --cov-report xml:cov.xml --instafail"
